language: python
email:
    recipients:
      - OMC-team@cern.ch
      - efol@cern.ch
    on_success: always
    on_failure: always
python:
 - "2.7-minimal"
env:
 - EXCITATION=--acd
 - EXCITATION=--adt 

script: python GetLLM/getllm_precision_check.py $EXCITATION --optics=40cm
